use_frameworks!

target 'ConstraintsMonitor_Example' do
  pod 'ConstraintsMonitor', :path => '../'

  target 'ConstraintsMonitor_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
